//--------------------------------------------------------------
// Lexical Grammer

%lex

%%

\s+        /* skip whitespace */

\d+        return 'NUMBER'

/lex

//--------------------------------------------------------------
// Syntactic Grammer

%%

E
    : T E'
    ;

E'
    : '+' T E'
    | 
    ;

T
    : F T'
    ;

T'
    : '*' F T'
    | 
    ;

F
    : NUMBER
    | '(' E ')'
    ;